# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  omniauth_provider_key: 179705079256539 
  omniauth_provider_secret: dedd7cccdfc9d23aa9464e85087aade5de
  domain_name: example.com
  secret_key_base: f22f884249e6982de11a51b50360b5602b2913738dc69709ca47621092923ab969e5ce3378073f6b6bc1527a534f1f937cddaf984f93a11f5b7d30f6f50ea56b

test:
  secret_key_base: f2baf6ed8709258841edbb8aedd0ca2d58c325ea5888b6cb88f4ee3fe50cc89e992621ee405718add1e8690032dfc2a28b2c31522964a36d1008e665c3df8f3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  omniauth_provider_key: 179705079256539 
  omniauth_provider_secret: dedd7cccdfc9d23aa9464e85087aade5de
  #domain_name: https://www.facebook.com/Camilo.Alzat
  secret_key_base:  f2baf6ed8709258841edbb8aedd0ca2d58c325ea5888b6cb88f4ee3fe50cc89e992621ee405718add1e8690032dfc2a28b2c31522964a36d1008e665c3df8f3e
